trigger:
  - main

stages:
  - stage: assemble
    displayName: Assemble
    jobs:
      - job: build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: UseDotNet@2
            displayName: 'Install .NET Core SDK 6.0'
            inputs:
              packageType: sdk
              version: 6.0.x
          - task: ShellScript@2
            displayName: 'NUKE Publish'
            inputs:
              scriptPath: ./build.sh
              args: >
                publish
