trigger:
  - main

stages:
  - stage: assemble
    displayName: Assemble
    jobs:
      - job: build
        displayName: Build
        pool:
          vmImage: windows-latest
        steps:
          - task: UseDotNet@2
            displayName: 'Install .NET Core SDK 6.0'
            inputs:
              packageType: sdk
              version: 6.0.x
          - task: CmdLine@2
            displayName: 'Precreate build directories'
            inputs:
              script: 'mkdir artifacts'
          - task: CmdLine@2
            displayName: 'NUKE publish'
            inputs:
              script: './build.ps1 publish'
